### ISSUE TITLE
update repo status to abandoned

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/lessons#3]
current developments of lesson in the tutorials repo https://github.com/epiverse-trace/tutorials/
ref: https://www.repostatus.org/

**Comment by chartgerink** [comment]
We could archive this repo in case we know this won't be worked on?

https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories

**Comment by avallecam** [comment]
Thank you for looking for this 

> We could archive this repo in case we know this won't be worked on?

I agree. I filled the content from the about page to an issue https://github.com/epiverse-trace/tutorials/issues/142 and project https://github.com/orgs/epiverse-trace/projects/32 to use this content in an evaluation phase

I'll move on with the archive of the project.
